### ISSUE TITLE
[New Feature] Should add way to validate --option

### ISSUE THREAD

**Issue by huypx-nfq** [cerbero90/command-validator#5]
Usually, I use --option instead of argument in case like.
`php artisan command --user=1 --date=1 --partner=1`
so any option can be optional and that value will be default.

If I use argument. `php artisan command 1` I don't know which argument is it.

**Comment by cerbero90** [comment]
Hi @huypx-nfq, not sure if I understand your issue but both arguments and options can be validated, e.g.:

```php
protected function rules()
{
    return [
        'argument' => 'some|validation|rules',
        'option' => 'some|validation|rules',
    ];
}
```

Please let me know if you have issues or if I misunderstood what you meant
